<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Momento')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/main.css'))
            ->prependStylesheet("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
            ->prependStylesheet("https://fonts.googleapis.com/css?family=Indie+Flower|Open+Sans+Condensed:300|Pacifico|Slabo+27px")
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js')
            ->appendFile($this->basePath('js/common.js'))
        ?>

    </head>
    <body>
       <div class="container">
            <header class="main_header row">
                <div class="col-md-12" id="header_wrapper">
                    <h2 class="site_name hidden-xs">Momento</h2>
                    <div class="dropdown visible-xs">
                        <div class="dropdown-toggle hamburger visible-xs" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            <span class="glyphicon glyphicon-menu-hamburger"></span>
                        </div>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="#">Donate</a></li>
                            <li><a href="#">Our mission</a></li>
                            <li><a href="#">Top posts</a></li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Log in</a></li>
                        </ul>
                    </div>
                    <div class="centered_logo"><h2 class="site_name visible-xs">Momefnto</h2></div>
                    <div class="drop_down">
                    </div>
                    <div class="menu_and_avatar">
                        <ul class="main_menu hidden-xs">
                            <li><a href="#">Donate</a></li>
                            <li><a href="#">Our mission</a></li>
                            <li><a href="#">Top posts</a></li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Log in</a></li>
                        </ul>
                        <img src="" style="display:none" alt=avatar id="avatar_pic">
                    </div>
                </div>
            </header>
        </div>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer class="main_footer">
            <small>&copy 2017. NIC SPB ETU. All rights reserved.</small>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
