-- MySQL Script generated by MySQL Workbench
-- Сб 18 фев 2017 17:47:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema momento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema momento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `momento` DEFAULT CHARACTER SET utf8 ;
USE `momento` ;

-- -----------------------------------------------------
-- Table `momento`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `momento`.`blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(350) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = 'Blogs data';


-- -----------------------------------------------------
-- Table `momento`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `momento`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT ' ',
  `age` SMALLINT NULL DEFAULT NULL,
  `registration_date` DATETIME NOT NULL,
  `lastseen_date` DATETIME NOT NULL,
  `level` SMALLINT NOT NULL DEFAULT 5,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB
COMMENT = 'Users accounts\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
