<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<section class="container row main_content" style="display: table">
    <div class="col-md-3 left_section hidden-xs hidden-sm" style="display: table-cell">
        <div class="right_search input-group">
            <input class="form-control" placeholder="Search query here">
            <a class="right_search_button input-group-addon glyphicon glyphicon-search" aria-hidden="true"></a>
        </div>

        <div class="catalogue">
            <h2>Categories</h2>
            <br>
            <ul>
                <li><a href="#">Automobiles</a></li>
                <li class="li_level_2"><a href="#">Reviews</a></li>
                <li class="li_level_2"><a href="#">Buy/Sell</a></li>
                <li class="li_level_2"><a href="#">News</a></li>
                <li><a href="#">Relationship</a></li>
                <li><a href="#">Movies</a></li>
                <li><a href="#">Humor and stuff</a></li>
                <li><a href="#">Computer video games</a></li>
                <li><a href="#">Music</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-7 center_section" style="display: table-cell" >
        <div class="center_section_wrapper">
            <h2 class="create_post_label"><a href="#">Create Post</a></h2>
            
            <?php foreach ($blogs as $blog): ?>
            <div class="post_card">
                <header class="post_header">
                    <span class="glyphicon glyphicon-user post_avatar">
                    </span>
                    <div class="post_info">
                        <p><?= $this->escapeHtml($blog->getAuthorDisplayName()) ?></p>
                        <small><?= $this->escapeHtml($blog->created) ?></small>
                    </div>
                    <h2><?= $this->escapeHtml($blog->title) ?></h2>
                </header>
                <div class="post_content">
                    <?= $this->escapeHtml($blog->description) ?>
                </div>
            </div>
            <?php endforeach; ?>
            
        </div>
    </div>
    <div class="col-md-2" style="display: table-cell" ></div>
</section>